# cis-baseline.yaml
---

- hosts: svr1
  tasks:
    
    # 1.1 Password Policy
    - name: Enforce password history' is set to '24 or more password(s)'
      community.windows.win_security_policy:
        section: System Access
        key: PasswordHistorySize
        value: 24

    - name: Ensure 'Maximum password age' is set to '60 or fewer days, but not 0'
      community.windows.win_security_policy:
        section: System Access
        key: MaximumPasswordAge 
        value: 60

    - name: Ensure 'Minimum password age' is set to '1 or more day(s)'
      community.windows.win_security_policy:
        section: System Access
        key: MinimumPasswordAge 
        value: 1 

    - name: Ensure 'Minimum password length' is set to '14 or more character(s)'
      community.windows.win_security_policy:
        section: System Access
        key: MinimumPasswordLength  
        value: 14

    - name: Ensure 'Password must meet complexity requirements' is set to 'Enabled'
      community.windows.win_security_policy:
        section: System Access
        key: PasswordComplexity  
        value: 1

    - name: Ensure 'Store passwords using reversible encryption' is set to 'Disabled'
      community.windows.win_security_policy:
        section: System Access
        key: ClearTextPassword  
        value: 0 

    #2.3.4 Devices

    - name: Ensure 'Devices Allowed to format and eject removable media' is set to 'Administrators'"
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: "AllocateDASD"
        data: "0"
        type: dword


    - name: Ensure 'Devices Prevent users from installing printer drivers' is set to 'Enabled
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers
        name: "AddPrinterDrivers"
        data: "1"
        type: dword

    #Interactive logon

    - name: "Ensure 'Interactive logon: Do not display last user name' is set to 'Enabled'"
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: "DontDisplayLastUserName"
        data: "1"
        type: dword

    - name: "Ensure 'Interactive logon: Do not require CTRL+ALT+DEL' is set to 'Disabled'"
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: "DisableCAD"
        data: "0"
        type: dword

    - name: "Ensure 'Interactive logon: Machine inactivity limit' is set to '900 or fewer second(s), but not 0'"
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: "InactivityTimeoutSecs"
        data: "900"
        type: dword

    - name: "Configure 'Interactive logon: Message text for users attempting to log on'"
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: "LegalNoticeText"
        data: "You must have explicit, authorized permission to access this system. Unauthorized attempts and actions to access or use this system may result in civial and/or criminal penalties. All activities performed on this device are logged and monitored."
        type: string

    - name: "Configure'Interactive logon: Message title for users attempting to log on'"
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: "LegalNoticeCaption"
        data: "UNAUTHORIZED ACCESS TO THIS SYSTEM IS PROHIBITED"
        type: string

    - name: "Ensure 'Interactive logon: Prompt user to change password before expiration' is set to 'between 5 and 14 days'"
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: "PasswordExpiryWarning"
        data: "14"
        type: dword

    - name: "Ensure 'Interactive logon: Require Domain Controller Authentication to unlock workstation' is set to 'Enabled'"
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: "ForceUnlockLogon"
        data: "1"
        type: dword

    - name: "Ensure 'Interactive logon: Smart card removal behavior' is set to 'Lock Workstation' or higher"
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: "ScRemoveOption"
        data: "1"
        type: string


    # Account Lockout

    - name: Ensure 'Account lockout threshold' is set to '10 or fewer invalid logon attempt(s), but not 0'
      community.windows.win_security_policy:
        section: System Access
        key: LockoutBadCount  
        value: 10    

    - name: Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'
      community.windows.win_security_policy:
        section: System Access
        key: ResetLockoutCount
        value: 15


    # Microsoft network client

    - name: "Ensure 'Microsoft network client: Digitally sign communications (always)' is set to 'Enabled'"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
        name: "RequireSecuritySignature"
        data: "1"
        type: dword

    - name: "Ensure 'Microsoft network client: Digitally sign communications (if server agrees)' is set to 'Enabled'"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
        name: "EnableSecuritySignature"
        data: "1"
        type: dword

    - name: "Ensure 'Microsoft network client: Send unencrypted password to third-party SMB servers' is set to 'Disabled'"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
        name: "EnablePlainTextPassword"
        data: "0"
        type: dword

    #Network Security

    - name: "Ensure 'Network security: Allow Local System to use computer identity for NTLM' is set to 'Enabled'"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
        name: "UseMachineId"
        data: "1"
        type: dword

    - name: "Ensure 'Network security: Allow LocalSystem NULL session fallback' is set to 'Disabled'"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
        name: "RestrictAnonymous"
        data: "1"
        type: dword

    - name: "Ensure 'Network Security: Allow PKU2U authentication requests to this computer to use online identities' is set to 'Disabled'"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\pku2u
        name: "AllowOnlineID"
        data: "1"
        type: dword

    - name: "Ensure 'Network security: Configure encryption types allowed for Kerberos' is set to 'AES128_HMAC_SHA1, AES256_HMAC_SHA1, Future encryption types'"
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters
        name: "SupportedEncryptionTypes"
        data: "2147483640"
        type: dword

    - name: "Ensure 'Network security: Do not store LAN Manager hash value on next password change' is set to 'Enabled'"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
        name: "NoLMHash"
        data: "1"
        type: dword

    - name: "Ensure 'Network security: LAN Manager authentication level' is set to 'Send NTLMv2 response only. Refuse LM & NTLM'"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
        name: "LmCompatibilityLevel"
        data: "5"
        type: dword

    - name: "Ensure 'Network security: LDAP client signing requirements' is set to 'Negotiate signing' or higher"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LDAP
        name: "LDAPClientIntegrity"
        data: "1"
        type: dword

    - name: "Ensure 'Network security: Minimum session security for NTLM SSP based (including secure RPC) clients' is set to 'Require NTLMv2 session security, Require 128-bit encryption'"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
        name: "NTLMMinClientSec"
        data: "537395200"
        type: dword

    - name: "Ensure 'Network security: Minimum session security for NTLM SSP based (including secure RPC) servers' is set to 'Require NTLMv2 session security, Require 128-bit encryption'"
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
        name: "NTLMMinServerSec"
        data: "537395200"
        type: dword
        
    # Shutdown

    - name: "Ensure 'Shutdown: Allow system to be shut down without having to log on' is set to 'Disabled'"
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System:ShutdownWithoutLogon
        name: "ShutdownWithoutLogon"
        data: "1"
        type: dword

    - name: "Ensure 'Windows Firewall: Domain: Firewall state' is set to 'On (recommended)'"
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\DomainProfile
        name: "EnableFirewall"
        data: "1"
        type: dword


    - name: "Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'"
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
        name: "NoLockScreenCamera"
        data: "1"
        type: dword


    - name: "Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'"
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
        name: "NoLockScreenSlideshow"
        data: "1"
        type: dword